runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

env_variables:
    #Firebase project id
    FIREBASE_PROJECT_ID: 'mcc-fall-2017-g08'
    GOOGLE_APPLICATION_CREDENTIALS: '/Users/Qahwi/.config/gcloud/application_default_credentials.json'
