runtime: python
api_version: 1
threadsafe: true
env: flex
entrypoint: gunicorn -b :$PORT main:app

#handlers:
#- url: /static
#  static_dir: static
#- url: /.*
#  script: main.app

env_variables:
    #Firebase project id
    #FLASK_APP: 'main.py'
    FIREBASE_PROJECT_ID: 'mcc-fall-2017-g08'
    #GOOGLE_APPLICATION_CREDENTIALS: '/Users/Qahwi/.config/gcloud/application_default_credentials.json'

skip_files:
  - venv/
